### ISSUE TITLE
Adding volume measurement devices

### ISSUE THREAD

**Issue by baonguyen21** [OPEnSLab-OSU/eDNA-Server#10]
The outflow of the system use an MS580302BA01 barometric sensor. This sensor has the worst resolution (over sampling ratio 256) to be 0.13mbar which equal roughly 1.3mm of water column. Best resolution (over sampling ratio 4096) is 0.24 mm of water column. 

The old method is to use two sensor, one in air (0x76) and one in the outflow cylindrical measurement container (0x77). Due to the accuracy of the sensor, we are not getting the same atmospheric pressure when both is open to air.

Since we are only interested in measuring water depth in the container, only one sensor should be used. Here are the steps:

- Empty outflow container, read in sensor baseline (change with temperature) <- How much does temperature affect water reading?
- Water will enter the container in Sample and Dry State
- Reading should be collected in the beginning of the Preserve Stage (alcohol take some time to travel to the container)
- Empty the outflow container after Preserve State

**Comment by kawinie** [comment]
Ok seems like you want to take reference water level on demand. Easy thing to do.

**Comment by baonguyen21** [comment]
The outflow pump is hooked up to TPIC0, valve 6

**Comment by kawinie** [comment]
> The outflow pump is hooked up to TPIC0, valve 6

You mean pin 6 (0-indexed)?

**Comment by baonguyen21** [comment]
> > The outflow pump is hooked up to TPIC0, valve 6
> 
> You mean pin 6 (0-indexed)?

Yes!

**Comment by baonguyen21** [comment]
A new flow measurement device has been detected! We need to allocate one analog pin for reading interrupt and then count the # of interrupt over 1 sec for Hz. The eq has been provided to Kawin for an easier Hz to mL/min conversion
