### ISSUE TITLE
Testing Pre-check

### ISSUE THREAD

**Issue by kawinie** [OPEnSLab-OSU/eDNA-Server#4]
## Pre-check list ✔️ 
- [x] **VSCode Live Share for realtime collaboration**
- [x] **Get project to compile using git submodule** 
Look in [develop](https://github.com/OPEnSLab-OSU/eDNA-Server/tree/develop) for instructions. 
- [x] **Upload to Feather M0** 
After you compile successfully, click the upload button in the status bar. PlatformIO should automatically find a serial port of the Feather when connected.
- [x] **Clone and build [eDNA Interface](https://github.com/OPEnSLab-OSU/eDNA-Interface/tree/develop)** 
Ping me if you are not familiar with NPM. You should first `npm install`  all dependencies then run `npx webpack --mode production` in working directory. The command triggers production build of the interface using WebPack. You should now see `index.html.gz` file in `dist` directory. Renaming this file to `index.gz` then copy it, together with the given SD template, over to the root folder of the SD card. 
- [x] **Transfer web files to SD card** 
Ping me after you completed this. You need to enable serving `index.gz` in `Application.cpp`.
- [x] **Connect to "eDNA-test" network** 
Use Firefox or Chrome for the best experience. 🔥 🔥 🔥 
- [x] 💰  **Profit!** 💰 

**Note**
Please contact 🤙  me after you complete each task or if you encounter any problem. Because I am constantly pushing new commits over, so you should pull changes from upstream often. Sometimes, the software reset (performed automatically by when uploading from PlatformIO) causes Feather to get stuck in upload mode (indicated by flashing red LED 🚨). If this happens, press the reset button twice quickly then try upload again.

**Another Note**
Click the offline button in the interface to start receiving updates.<img width="60" alt="Screen Shot 2020-07-06 at 9 40 46 AM" src="https://user-images.githubusercontent.com/39807451/86550519-c888c080-bf6c-11ea-8a23-2c9d1081ed97.png">

**SD Template**
[sd-template.zip](https://github.com/OPEnSLab-OSU/eDNA-Server/files/4849005/sd-template.zip)

## Update
Here is a pre-build interface that you can just copy over to the sd card
[interface.zip](https://github.com/OPEnSLab-OSU/eDNA-Server/files/4875336/interface.zip)

**Comment by baonguyen21** [comment]
![image](https://user-images.githubusercontent.com/48141945/86176490-dc01da80-bad9-11ea-875c-091815217970.png)
 
Able to view the website in FireFox, not Chrome. I can create task but not able to select any valve and save/delete the task.
The local time RTC did not show any data. Valve selection layout does not work.

**Comment by zimmermannliam** [comment]
Comments for reference:

Feather upload is done via usb and PIO
Current issue: hangs on "Forcing reset using 1200bps open/close on COM Port" - probably need some software?
Need to define "given sd template"
Make it more obvious that npm install will install the dependencies by default, not that we have to do it ourself

**Comment by kawinie** [comment]
@zimmermannliam 
>  hangs on "Forcing reset using 1200bps open/close on COM Port"

If you see a slow blinking red-light, that means the software reset wasn't working. You need to press the reset button twice to enable upload mode.

> Need to define "given sd template"

For the SD template, make sure to use the one I have uploaded.

> obvious that npm install will install the dependencies by default

 Yeah `npm install` installs all the dependencies defined in the `package.json`. The exact commands you need to run are `tagged`. I'll make sure to be put them in separate line in the future.

@nguyenb5 
I did say that you should contact me after you got the interface to display because there are more instructions 🤣. You need to press on the offline button to receive status updates. I did this for testing other aspects of the system and didn't want to see all the logs. New version has both compile-time and runtime log verbosity implemented. 

Make sure to select the valves from the valve overview first before modifying the task. This is a side effect of Redux re-rendering that I should have a fix by Sunday/Monday after conversion to TS.

**Comment by baonguyen21** [comment]
@kawinie 

I was able to click OFFLINE, but still unable to save the task.

**Comment by kawinie** [comment]
@nguyenb5 @zimmermannliam 
The interface and the server have been updated and pushed.

**Server**
You should `git reset --hard` then `git pull`. Git should resolves dependencies automatically. You can then comment out `develop()` and enable serving `index.gz` in `Application.cpp`.

**Interface**
You can use the pre-build interface application I upload in the original post if you can't compile. Just transfer everything to the root of the sd card.

**To enable more valves**
You can also specify what valves should be available for use in `config.js` under "freeValves". Then enter `reset valves` when connected to serial monitor.

**Comment by zimmermannliam** [comment]
I'm having trouble getting to the actual interface (192.168.1.1), but the wifi works.

**Comment by kawinie** [comment]
@zimmermannliam The program is in `DEBUG` mode, meaning that it's waiting for serial port to connect. Turn on the serial monitor then it should work. Or have you commented out `develop()`?
