### ISSUE TITLE
Preload Protocol Testing

### ISSUE THREAD

**Issue by kawinie** [OPEnSLab-OSU/eDNA-Server#9]
## Preload Water 

|      State       | Motor Status |  Inlet Valves  | Filter valve | Outlet valves | Duraration | Next condition |                                   Target                                   |
| ---------------- | ------------ | -------------- | ------------ | ------------- | ---------- | -------------- | -------------------------------------------------------------------------- |
| Flush            | Forward      | Water valve ON | OFF          | ON            | 10s        |                |                                                                            |
| Offshoot Preload | Forward      | Water valve ON | ON           | OFF           | 2~3 s      | Time           | Special state, only run once in the begining, Flush then Preload offshoot. |

**Comment by baonguyen21** [comment]
Kawin, I was unable to pull the code that has this protocol. I do have the new.cpp files but not sure if I need new interface code or not.

My latest develop pull only perform old routine. Flush  Sample Dry Preserve

**Comment by baonguyen21** [comment]
I changed the BallValve pins in ball.cpp.
Corrected pins:
![image](https://user-images.githubusercontent.com/48141945/87353481-bd580680-c511-11ea-9963-91685f207d8e.png)

Request: The code run all 24 valves but I only have 3. I had to changed the for loop and the transition time to do just 3.

![image](https://user-images.githubusercontent.com/48141945/87349077-9fd36e80-c50a-11ea-8afd-45390c90eebe.png)

**Comment by kawinie** [comment]
Hey thanks.  I think the best thing to do here is to preload water according to valves in config.js?

**Comment by kawinie** [comment]
I updated Preloading to preload only valves specified in config.js. closes #9

**Comment by kawinie** [comment]
closes #9
